In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/india-ev-market-data/Vehicle Class - All.csv
/kaggle/input/india-ev-market-data/ev_sales_by_makers_and_cat_15-24.csv
/kaggle/input/india-ev-market-data/EV Maker by Place.csv
/kaggle/input/india-ev-market-data/OperationalPC.csv
/kaggle/input/india-ev-market-data/ev_cat_01-24.csv

In [2]:
table1=pd.read_csv("/kaggle/input/india-ev-market-data/EV Maker by Place.csv")
print(table1)

                       EV Maker        Place        State
0                   Tata Motors         Pune  Maharashtra
1             Mahindra Electric    Bengaluru    Karnataka
2                  Ather Energy    Bengaluru    Karnataka
3                 Hero Electric    New Delhi        Delhi
4                  Ola Electric  Krishnagiri   Tamil Nadu
..                          ...          ...          ...
57          YC Electric Vehicle        Delhi        Delhi
58  Dilli Electric Auto Pvt Ltd    New Delhi        Delhi
59           Electrotherm India    Ahmedabad      Gujarat
60        Lohia Auto Industries     Kashipur  Uttarakhand
61                 Euler Motors    New Delhi        Delhi

[62 rows x 3 columns]

In [3]:
table2=pd.read_csv("/kaggle/input/india-ev-market-data/OperationalPC.csv")
print(table2)

                State  No. of Operational PCS
0   Andaman & Nicobar                       3
1      Andhra Pradesh                     327
2   Arunachal Pradesh                       9
3               Assam                      86
4               Bihar                     124
5          Chandigarh                      12
6        Chhattisgarh                     149
7         D&D and DNH                       1
8               Delhi                    1886
9                 Goa                     113
10            Gujarat                     476
11            Haryana                     377
12   Himachal Pradesh                      44
13  Jammu and Kashmir                      47
14          Jharkhand                     135
15          Karnataka                    1041
16             Kerala                     852
17        Lakshadweep                       1
18     Madhya Pradesh                     341
19        Maharashtra                    3079
20            Manipur                      17
21          Meghalaya                      21
22           Nagaland                       6
23             Odisha                     198
24        Pondicherry                      23
25             Punjab                     158
26          Rajasthan                     500
27             Sikkim                       2
28         Tamil Nadu                     643
29          Telangana                     481
30            Tripura                      18
31      Uttar Pradesh                     582
32        Uttarakhand                      76
33        West Bengal                     318

In [4]:
table3=pd.read_csv("/kaggle/input/india-ev-market-data/Vehicle Class - All.csv")
print(table3)

                      Vehicle Class Total Registration
0   FOUR WHEELER (INVALID CARRIAGE)             21,346
1               HEAVY GOODS VEHICLE          58,70,865
2               HEAVY MOTOR VEHICLE           1,02,965
3           HEAVY PASSENGER VEHICLE           8,28,189
4               LIGHT GOODS VEHICLE        1,02,49,591
5               LIGHT MOTOR VEHICLE        6,50,61,773
6           LIGHT PASSENGER VEHICLE          43,43,410
7              MEDIUM GOODS VEHICLE           8,75,789
8              MEDIUM MOTOR VEHICLE           1,94,600
9          MEDIUM PASSENGER VEHICLE           3,25,015
10       OTHER THAN MENTIONED ABOVE          11,26,398
11                THREE WHEELER(NT)           6,79,804
12                 THREE WHEELER(T)        1,07,08,473
13   TWO WHEELER (INVALID CARRIAGE)           1,10,788
14                  TWO WHEELER(NT)       27,49,71,646
15                   TWO WHEELER(T)           1,29,181

In [5]:
table4=pd.read_csv("/kaggle/input/india-ev-market-data/ev_cat_01-24.csv")
print(table4)

         Date  FOUR WHEELER (INVALID CARRIAGE)  HEAVY GOODS VEHICLE  \
0           0                                0                    0
1    01/01/01                                0                    1
2    01/01/02                                0                    2
3    01/01/03                                0                    1
4    01/01/04                                0                    2
..        ...                              ...                  ...
279  01/12/19                                0                    0
280  01/12/20                                0                    0
281  01/12/21                                2                    0
282  01/12/22                                0                    0
283  01/12/23                                3                   16

     HEAVY MOTOR VEHICLE  HEAVY PASSENGER VEHICLE  LIGHT GOODS VEHICLE  \
0                      0                        0                    0
1                      0                        0                    9
2                      1                        0                  266
3                      2                        0                   35
4                      0                        1                   14
..                   ...                      ...                  ...
279                    0                       41                   18
280                    0                       10                    1
281                    1                      218                   16
282                    0                      146                   30
283                    0                      491                  254

     LIGHT MOTOR VEHICLE  LIGHT PASSENGER VEHICLE  MEDIUM GOODS VEHICLE  \
0                      0                        0                     0
1                     15                        1                     0
2                     11                        5                     0
3                     15                        1                     0
4                     17                        1                     0
..                   ...                      ...                   ...
279                   57                       49                     0
280                  505                       18                     0
281                 2483                      133                     0
282                 2925                      915                     0
283                 7008                      499                     0

     MEDIUM PASSENGER VEHICLE  MEDIUM MOTOR VEHICLE  \
0                           0                     0
1                           0                     0
2                           0                     0
3                           0                     0
4                           0                     1
..                        ...                   ...
279                        10                     0
280                         0                     0
281                         2                     0
282                        15                     0
283                        86                     0

     OTHER THAN MENTIONED ABOVE  THREE WHEELER(NT)  \
0                             0                  0
1                             2                  0
2                             0                  0
3                             1                  0
4                             2                  0
..                          ...                ...
279                         197                 15
280                         124                 17
281                         124                 17
282                         673                 35
283                           0                  7

     TWO WHEELER (INVALID CARRIAGE)  THREE WHEELER(T)  TWO WHEELER(NT)  \
0                                 0                 0                0
1                                 0                 2               62
2                                 0                 2               11
3                                 0                 9               18
4                                 0                 1               21
..                              ...               ...              ...
279                               1             14412             1900
280                               1             10230             4564
281                               0             24115            26150
282                               0             35604            64525
283                               0             57647            75748

     TWO WHEELER(T)
0                 0
1                 0
2                 0
3                 0
4                 0
..              ...
279             333
280             384
281             494
282             138
283             188

[284 rows x 17 columns]

In [6]:
table5=pd.read_csv("/kaggle/input/india-ev-market-data/ev_sales_by_makers_and_cat_15-24.csv")
print(table5)

     Cat                                            Maker  2015  2016  2017  \
0     3W                      "VOLVO GROUP INDIA PVT LTD"     0     0    31
1     3W                           3EV INDUSTRIES PVT LTD     0     0     0
2     2W                           3GB TECHNOLOGY PVT LTD     0     0     0
3     3W                           3GB TECHNOLOGY PVT LTD     0     1     1
4     3W                    3S INDUSTRIES PRIVATE LIMITED     0     0     0
...   ..                                              ...   ...   ...   ...
1381  2W        ZHEJIANG LUYUAN (IMPORTER: DYNAM EV TECH)     0     0     0
1382  2W  ZHEJIANG TIANYING  (IMPORTER: NEWTRON ELECTRIC)     0     0     0
1383  2W          ZHONGHUALONG (IMPORTER: POWORO PVT LTD)     0     0     0
1384  2W           ZHONGXING (IMPORTER:GREENO AUTOMOBILE)     0     0     0
1385  3W                      ZOHAN TRADERS AND BIG METRO     0     0     0

      2018  2019  2020  2021  2022  2023  2024
0       12     0     0     0     0     0     0
1        0     0     0   112   390   545    51
2        1     0     0     0     0     0     0
3        0     0     0     0     0     0     0
4        0    48    66    43    68   266   578
...    ...   ...   ...   ...   ...   ...   ...
1381     0     0     0     0    21    45     9
1382     0     0     0     0     0    64     6
1383     0     0     0     0     0     0    54
1384     0     0     0     0     0     0     5
1385     0     0     0     0     5   131    74

[1386 rows x 12 columns]

In [7]:
table1.drop_duplicates(inplace=True)
print(table1.to_string())

                       EV Maker          Place           State
0                   Tata Motors           Pune     Maharashtra
1             Mahindra Electric      Bengaluru       Karnataka
2                  Ather Energy      Bengaluru       Karnataka
3                 Hero Electric      New Delhi           Delhi
4                  Ola Electric    Krishnagiri      Tamil Nadu
5                 Ashok Leyland        Chennai      Tamil Nadu
6             TVS Motor Company          Hosur      Tamil Nadu
7                    Bajaj Auto           Pune     Maharashtra
8                MG Motor India          Halol         Gujarat
9           Hyundai Motor India        Chennai      Tamil Nadu
10                Revolt Motors        Gurgaon         Haryana
11              Ampere Vehicles     Coimbatore      Tamil Nadu
12             Okinawa Autotech        Bhiwadi       Rajasthan
13         Kinetic Green Energy           Pune     Maharashtra
14                    BYD India  Sriperumbudur      Tamil Nadu
15                     JBM Auto      Faridabad         Haryana
16             Piaggio Vehicles       Baramati     Maharashtra
17                Hero MotoCorp      Dharuhera         Haryana
18            Etrio Automobiles      Hyderabad       Telangana
19              Triton Electric           Bhuj         Gujarat
20                Simple Energy      Bengaluru       Karnataka
21             Minda Industries           Pune     Maharashtra
22             Exide Industries        Kolkata     West Bengal
23               Greaves Cotton         Mumbai     Maharashtra
24          Maruti Suzuki India        Manesar         Haryana
25                Renault India        Chennai      Tamil Nadu
26                Citroën India    Thiruvallur      Tamil Nadu
27                   Audi India     Aurangabad     Maharashtra
28          Mercedes-Benz India         Chakan     Maharashtra
29             Kia Motors India      Anantapur  Andhra Pradesh
30                 Volvo Eicher      Pithampur  Madhya Pradesh
31                   JSW Energy         Mumbai     Maharashtra
32            Olectra Greentech      Hyderabad       Telangana
33                 Force Motors           Pune     Maharashtra
34              TVS Electronics        Chennai      Tamil Nadu
35                Royal Enfield        Chennai      Tamil Nadu
36                 Bharat Forge           Pune     Maharashtra
37             Hindustan Motors      Uttarpara     West Bengal
38                    Atul Auto         Rajkot         Gujarat
39                    SML Isuzu          Ropar          Punjab
40                Mahindra Reva      Bengaluru       Karnataka
41         Ajanta Manufacturing          Morbi         Gujarat
42                   Tata Power         Mumbai     Maharashtra
43       Ashok Leyland (EV Bus)          Alwar       Rajasthan
44        HOP Electric Mobility         Jaipur       Rajasthan
45         Omega Seiki Mobility      Faridabad         Haryana
46              Bajaj Auto (EV)         Akurdi     Maharashtra
47        Tata AutoComp Systems           Pune     Maharashtra
48                  Bosch India      Bengaluru       Karnataka
49        Lohia Auto Industries       Kashipur     Uttarakhand
50          Saera Electric Auto        Bhiwadi       Rajasthan
51                 Jezza Motors        Kolkata     West Bengal
52    Altigreen Propulsion Labs      Bengaluru       Karnataka
53           Terra Motors India       Gurugram         Haryana
54            Gayam Motor Works      Hyderabad       Telangana
55    Kinetic Green (3-Wheeler)     Ahmednagar     Maharashtra
56    Greaves Electric Mobility     Coimbatore      Tamil Nadu
57          YC Electric Vehicle          Delhi           Delhi
58  Dilli Electric Auto Pvt Ltd      New Delhi           Delhi
59           Electrotherm India      Ahmedabad         Gujarat
61                 Euler Motors      New Delhi           Delhi

In [8]:
table2.drop_duplicates(inplace=True)
print(table2.to_string())

                State  No. of Operational PCS
0   Andaman & Nicobar                       3
1      Andhra Pradesh                     327
2   Arunachal Pradesh                       9
3               Assam                      86
4               Bihar                     124
5          Chandigarh                      12
6        Chhattisgarh                     149
7         D&D and DNH                       1
8               Delhi                    1886
9                 Goa                     113
10            Gujarat                     476
11            Haryana                     377
12   Himachal Pradesh                      44
13  Jammu and Kashmir                      47
14          Jharkhand                     135
15          Karnataka                    1041
16             Kerala                     852
17        Lakshadweep                       1
18     Madhya Pradesh                     341
19        Maharashtra                    3079
20            Manipur                      17
21          Meghalaya                      21
22           Nagaland                       6
23             Odisha                     198
24        Pondicherry                      23
25             Punjab                     158
26          Rajasthan                     500
27             Sikkim                       2
28         Tamil Nadu                     643
29          Telangana                     481
30            Tripura                      18
31      Uttar Pradesh                     582
32        Uttarakhand                      76
33        West Bengal                     318

In [10]:
table3.drop_duplicates(inplace=True)
print(table3.to_string())

                      Vehicle Class Total Registration
0   FOUR WHEELER (INVALID CARRIAGE)             21,346
1               HEAVY GOODS VEHICLE          58,70,865
2               HEAVY MOTOR VEHICLE           1,02,965
3           HEAVY PASSENGER VEHICLE           8,28,189
4               LIGHT GOODS VEHICLE        1,02,49,591
5               LIGHT MOTOR VEHICLE        6,50,61,773
6           LIGHT PASSENGER VEHICLE          43,43,410
7              MEDIUM GOODS VEHICLE           8,75,789
8              MEDIUM MOTOR VEHICLE           1,94,600
9          MEDIUM PASSENGER VEHICLE           3,25,015
10       OTHER THAN MENTIONED ABOVE          11,26,398
11                THREE WHEELER(NT)           6,79,804
12                 THREE WHEELER(T)        1,07,08,473
13   TWO WHEELER (INVALID CARRIAGE)           1,10,788
14                  TWO WHEELER(NT)       27,49,71,646
15                   TWO WHEELER(T)           1,29,181

In [11]:
table4.drop_duplicates(inplace=True)
print(table4.to_string())

         Date  FOUR WHEELER (INVALID CARRIAGE)  HEAVY GOODS VEHICLE  HEAVY MOTOR VEHICLE  HEAVY PASSENGER VEHICLE  LIGHT GOODS VEHICLE  LIGHT MOTOR VEHICLE  LIGHT PASSENGER VEHICLE  MEDIUM GOODS VEHICLE  MEDIUM PASSENGER VEHICLE  MEDIUM MOTOR VEHICLE  OTHER THAN MENTIONED ABOVE  THREE WHEELER(NT)  TWO WHEELER (INVALID CARRIAGE)  THREE WHEELER(T)  TWO WHEELER(NT)  TWO WHEELER(T)
0           0                                0                    0                    0                        0                    0                    0                        0                     0                         0                     0                           0                  0                               0                 0                0               0
1    01/01/01                                0                    1                    0                        0                    9                   15                        1                     0                         0                     0                           2                  0                               0                 2               62               0
2    01/01/02                                0                    2                    1                        0                  266                   11                        5                     0                         0                     0                           0                  0                               0                 2               11               0
3    01/01/03                                0                    1                    2                        0                   35                   15                        1                     0                         0                     0                           1                  0                               0                 9               18               0
4    01/01/04                                0                    2                    0                        1                   14                   17                        1                     0                         0                     1                           2                  0                               0                 1               21               0
5    01/01/05                                0                    0                    0                        0                   10                   14                        1                     0                         0                     0                           0                  0                               0                 1               38               0
6    01/01/06                                0                    1                    0                        0                    9                   15                        1                     0                         0                     0                           2                  0                               0                 2               62               0
7    01/01/07                                0                    3                    3                        0                    7                   20                        0                     0                         0                     0                           0                  0                               0                 2              119               0
8    01/01/08                                0                    0                    2                        0                    6                   40                        3                     0                         0                     0                           2                  0                               0                 2              518               0
9    01/01/09                                0                    0                    0                        0                    2                   41                        0                     0                         0                     0                           1                  0                               0                 1              965               0
10   01/01/10                                0                    0                    0                        0                    7                   17                        0                     0                         0                     0                           0                  0                               0                 4              357               0
11   01/01/11                                0                    1                    0                        0                   48                   70                        0                     0                         0                     0                           0                  0                               0                 1              317               0
12   01/01/12                                0                    2                    0                        0                    8                   87                        5                     0                         0                     0                           0                  0                               0                 1              560               0
13   01/01/13                                0                    3                    1                        0                    5                   27                        1                     0                         0                     0                           0                  0                               0                 2              209               0
14   01/01/14                                0                    0                    0                        0                    6                   46                        1                     0                         0                     0                           1                  0                               0                 2              175               0
15   01/01/15                                0                    0                    0                        0                    5                   76                        0                     0                         0                     0                           0                  0                               0                 2               93               0
16   01/01/16                                1                    1                    0                        1                    4                   86                        7                     0                         0                     0                          15                  0                               0              1712              117               0
17   01/01/17                                0                    0                    0                        0                   10                   72                       21                     0                         0                     0                          16                  0                               0              4351              108               0
18   01/01/18                                0                    0                    0                        0                  112                   69                       27                     1                         0                     0                          47                 13                               0              8559              176               0
19   01/01/19                                0                    0                    0                        5                   11                   64                        9                     0                         0                     0                          10                  1                              24             10532             2514             208
20   01/01/20                                0                    0                    0                        2                    1                   84                      204                     0                         7                     0                          58                  7                               1             13550             2218             723
21   01/01/21                                0                    0                    0                       15                    0                  579                       73                     0                        24                     0                          74                 11                               0             10927             4967             360
22   01/01/22                                1                    0                    0                      126                   15                 1360                      202                     0                         2                     0                          79                 36                               0             19526            29511             631
23   01/01/23                                1                    0                    0                      138                   33                 2971                      472                     0                         1                     0                         171                 26                               2             34368            64561             141
24   01/01/24                                7                   21                    0                      543                  397                 7024                     1453                     0                         6                     0                           0                 10                               1             53451            82093              41
25   01/02/01                                0                    0                    0                        0                    7                   28                        0                     0                         0                     0                           0                  0                               0                 2               65               0
26   01/02/02                                0                    0                    1                        0                  324                    6                       11                     0                         0                     0                           0                  0                               0                 0               16               0
27   01/02/03                                0                    1                    0                        0                   52                   28                        4                     0                         0                     0                           0                  0                               0                 1               10               0
28   01/02/04                                0                    0                    0                        0                   10                    4                        0                     0                         0                     0                           0                  0                               0                 1               11               0
29   01/02/05                                0                    0                    0                        0                    8                   13                        1                     0                         0                     0                           0                  0                               0                 3               50               0
30   01/02/06                                0                    0                    0                        0                    7                   28                        0                     0                         0                     0                           0                  0                               0                 2               65               0
31   01/02/07                                0                    0                    4                        0                    4                   38                        1                     1                         0                     0                           1                  0                               0                 7              117               0
32   01/02/08                                0                    0                    0                        0                    7                   83                        1                     0                         0                     0                           2                  0                               0                 1              671               0
33   01/02/09                                0                    0                    1                        0                    4                   43                        0                     0                         0                     0                           1                  0                               0                 5              831               0
34   01/02/10                                0                    2                    0                        0                    1                   16                        2                     0                         0                     0                           0                  1                               0                10              342               0
35   01/02/11                                0                    2                    3                        0                   44                  164                        5                     0                         0                     0                           3                  0                               1                 6              889               0
36   01/02/12                                0                    2                    1                        0                    8                   67                        1                     0                         0                     0                           2                  0                               0                 5              635               0
37   01/02/13                                0                    0                    0                        0                    9                   21                        1                     0                         0                     0                           0                  0                               0                 4              201               0
38   01/02/14                                0                    3                    0                        1                   11                   28                        0                     0                         0                     0                           0                  0                               0                 0              130               0
39   01/02/15                                0                    2                    0                        0                    5                   62                        1                     0                         0                     0                           1                  0                               0                 3              109               0
40   01/02/16                                1                    1                    0                        0                   14                   61                        1                     0                         0                     0                          15                  0                               0              2287              119               0
41   01/02/17                                0                    0                    0                        0                   37                   54                       21                     0                         0                     0                          18                  0                               0              4203               75               0
42   01/02/18                                0                    0                    0                       11                   69                  117                       73                     0                         0                     0                          42                  2                               0              6902              156               0
43   01/02/19                                0                    0                    0                       25                    2                  157                       71                     0                        18                     0                          47                  2                               1              8784             3029              95
44   01/02/20                                0                    0                    0                       19                    2                  105                      387                     0                         0                     0                          79                 16                               0             13610             2164             190
45   01/02/21                                0                    0                    0                      133                    8                  586                       31                     0                        53                     0                         113                 24                               0             12535             6449             135
46   01/02/22                                1                    0                    0                      133                   15                 2308                      144                     0                         0                     0                          95                 26                               0             19608            35132             635
47   01/02/23                                1                    0                    0                      111                   81                 4366                      395                     0                        11                     0                          76                 32                               4             36053            65950             142
48   01/02/24                                3                   28                    0                      341                  489                 6845                      668                     0                         4                     0                           0                 13                               0             50622            82576             151
49   01/03/01                                0                    0                    2                        0                    6                   26                        0                     1                         0                     0                           2                  1                               0                 1               75               0
50   01/03/02                                0                    1                    0                        0                  881                   23                        8                     1                         0                     0                           0                  0                               0                 1                6               0

In [15]:
table1.value_counts()

EV Maker               Place      State
Ajanta Manufacturing   Morbi      Gujarat           1
Kia Motors India       Anantapur  Andhra Pradesh    1
Kinetic Green Energy   Pune       Maharashtra       1
Lohia Auto Industries  Kashipur   Uttarakhand       1
MG Motor India         Halol      Gujarat           1
                                                   ..
Hero MotoCorp          Dharuhera  Haryana           1
Hindustan Motors       Uttarpara  West Bengal       1
Hyundai Motor India    Chennai    Tamil Nadu        1
JBM Auto               Faridabad  Haryana           1
YC Electric Vehicle    Delhi      Delhi             1
Name: count, Length: 61, dtype: int64

In [ ]:
table5.drop_duplicates(inplace=True)
print(table5.to_string())

In [12]:
table1.head()

            EV Maker        Place        State
0        Tata Motors         Pune  Maharashtra
1  Mahindra Electric    Bengaluru    Karnataka
2       Ather Energy    Bengaluru    Karnataka
3      Hero Electric    New Delhi        Delhi
4       Ola Electric  Krishnagiri   Tamil Nadu

In [13]:
print(table2.sort_values(by="No. of Operational PCS"))

                State  No. of Operational PCS
17        Lakshadweep                       1
7         D&D and DNH                       1
27             Sikkim                       2
0   Andaman & Nicobar                       3
22           Nagaland                       6
2   Arunachal Pradesh                       9
5          Chandigarh                      12
20            Manipur                      17
30            Tripura                      18
21          Meghalaya                      21
24        Pondicherry                      23
12   Himachal Pradesh                      44
13  Jammu and Kashmir                      47
32        Uttarakhand                      76
3               Assam                      86
9                 Goa                     113
4               Bihar                     124
14          Jharkhand                     135
6        Chhattisgarh                     149
25             Punjab                     158
23             Odisha                     198
33        West Bengal                     318
1      Andhra Pradesh                     327
18     Madhya Pradesh                     341
11            Haryana                     377
10            Gujarat                     476
29          Telangana                     481
26          Rajasthan                     500
31      Uttar Pradesh                     582
28         Tamil Nadu                     643
16             Kerala                     852
15          Karnataka                    1041
8               Delhi                    1886
19        Maharashtra                    3079

In [14]:
max_row=table2[table2["No. of Operational PCS"]==table2["No. of Operational PCS"].max()]
print(max_row)

          State  No. of Operational PCS
19  Maharashtra                    3079

In [19]:
print(table3.sort_values(by='Total Registration'))

                      Vehicle Class Total Registration
4               LIGHT GOODS VEHICLE        1,02,49,591
2               HEAVY MOTOR VEHICLE           1,02,965
12                 THREE WHEELER(T)        1,07,08,473
13   TWO WHEELER (INVALID CARRIAGE)           1,10,788
15                   TWO WHEELER(T)           1,29,181
8              MEDIUM MOTOR VEHICLE           1,94,600
10       OTHER THAN MENTIONED ABOVE          11,26,398
0   FOUR WHEELER (INVALID CARRIAGE)             21,346
14                  TWO WHEELER(NT)       27,49,71,646
9          MEDIUM PASSENGER VEHICLE           3,25,015
6           LIGHT PASSENGER VEHICLE          43,43,410
1               HEAVY GOODS VEHICLE          58,70,865
5               LIGHT MOTOR VEHICLE        6,50,61,773
11                THREE WHEELER(NT)           6,79,804
3           HEAVY PASSENGER VEHICLE           8,28,189
7              MEDIUM GOODS VEHICLE           8,75,789

In [21]:
max_value=table3[table3["Total Registration"]==table3["Total Registration"].max()]
print(max_value)

          Vehicle Class Total Registration
7  MEDIUM GOODS VEHICLE           8,75,789